### ISSUE TITLE
[Bug]: `env` usage in the `action.yml` file

### ISSUE THREAD

**Issue by cicdguy** [insightsengineering/r-image-creator#6]
### What happened?

`env` is not a valid directive in the `action.yml` file. It's not part of the actions metadata syntax or schema. This needs to be fixed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by dgrassellyb** [comment]
(@cicdguy I saw you merged my latest changes on this, I close it !)
